FROM python:3.10.5

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/storage

CMD ["sh", "-c", "python main.py"]

VOLUME ["/app/storage"]
